title: Project
pages: false
files:
  sortable: true
  fields:
    gallerylink:
      label: Gallery link
      type:  text
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  pictures:
    label: Gallery
    type: gallery
